---@meta

--[[~ Updated: 2024/12/29 | Author(s): Gopher ]]
--
-- Backbone - An addon development framework for World of Warcraft.
--
--This program is free software: you can redistribute it and/or modify it under the terms
--of the GNU General Public License as published by the Free Software Foundation, either
--version 3 of the License, or (at your option) any later version.
--
--This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
--without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
--See the GNU General Public License <https://www.gnu.org/licenses/> for more details.

---
---?
---
---@class backbone.channel
---
---@field name string The unique name of the channel.
---@field owner backbone.addon The addon that owns the channel.
---@field access 'public'|'private' The access level of the channel.
---@field subscribers backbone.observable The observable handling subscribers.
---

---
---?
---
---@class backbone.channel-options
---
---@field owner backbone.addon The addon that owns the channel.
---@field name string The unique name of the channel.
---@field access? 'public'|'private' The access level of the channel.
---
